### ISSUE TITLE
pick a template to build off of from html5.up

### ISSUE THREAD

**Issue by robojukie** [robojukie/thegoats#2]
http://html5up.net

**Comment by robojukie** [comment]
http://html5up.net

**Comment by Ahkeem** [comment]
I do like the Halcyonic, Minimaxing, and the Alpha.
**The Alpha has a Login
~Ahkeem

**Comment by Azalia-Cyphers** [comment]
The Eventually template has a good login page, if we are only granting access once the user's email has been subscribed.
